dist: xenial
language: c
cache: ccache
addons:
  apt:
    update: true
  apt_packages:
      - libgmp-dev
      - libmpfr-dev
      - libflint-dev
      - libboost-dev
      - autoconf
      - automake
      - libtool
      - python-pip
      - python3-pip
      - python3-setuptools
env:
  - PY="2"
    EANTIC="no"
  - PY="2"
    EANTIC="yes"
  - PY="3"
    EANTIC="no"
  - PY="3"
    EANTIC="yes"
install:
  - export MAKE="make -j2"
  - export PYTHON="python${PY}"
  - export PIPINSTALL="pip${PY} install --no-index --no-deps -v"
  # install normaliz
  - ./.travis-install-normaliz.sh
  # install pynormaliz
  - sudo $PIPINSTALL .
script:
  - export OMP_NUM_THREADS=4
  - $PYTHON setup.py test
