dist: xenial
language: c
cache: ccache
addons:
  apt:
    update: true
  apt_packages:
      - libgmp-dev
      - libmpfr-dev
      - libflint-dev
      - libboost-dev
      - autoconf
      - automake
      - libtool
      - python-pip
      - python3-pip
      - python3-setuptools
env:
  - PY="2"
    EANTIC="no"
  - PY="2"
    EANTIC="yes"
  - PY="3"
    EANTIC="no"
  - PY="3"
    EANTIC="yes"
install:
  - export MAKE="make -j2"
  - export PYTHON="python${PY}"
  - export PIP="pip${PY}"
  - export PIPINSTALL="${PIP} install --no-index --no-deps -v"
  # install normaliz
  - ./.travis-install-normaliz.sh
  # install pynormaliz
  - sudo $PIPINSTALL .
script:
  - export OMP_NUM_THREADS=4
  # run tests
  - $PYTHON setup.py test
  # uninstall, make source distribution and reinstall from it
  # and check that the module can be imported
  - sudo $PIP uninstall -y PyNormaliz
  - make sdist
  - sudo $PIPINSTALL dist/PyNormaliz-*.tar.gz
  - $PYTHON -c "import PyNormaliz"
