dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
cache: ccache
addons:
  apt:
    update: true
  apt_packages:
      - libgmp-dev
      - libmpfr-dev
      - libflint-dev
      - libboost-dev
      - autoconf
      - automake
      - libtool
env:
  - EANTIC=no
  - EANTIC=yes

# send email notifications if master branch starts failing
# or stops failing
notifications:
  email:
    if: branch = master
    recipients:
      - max@quendi.de
      - wbruns@uos.de
    on_success: change
    on_failure: change

install:
  - export MAKEFLAGS="-j2"
  - export PIP=$(which pip) # workaround so that sudo uses correct pip
  # install normaliz
  - ./.travis-install-normaliz.sh
  # install pynormaliz
  - sudo $PIP install --no-index --no-deps -v .

script:
  - export OMP_NUM_THREADS=4
  # run tests
  - python setup.py test
  # uninstall, make source distribution and reinstall from it
  # and check that the module can be imported
  - sudo $PIP uninstall -y PyNormaliz
  - python setup.py sdist
  - sudo $PIP install --no-index --no-deps -v dist/PyNormaliz-*.tar.gz
  - python -c "import PyNormaliz"
