dist: xenial
language: python
python:
  - "2.7"
  - "3.6"
cache: ccache
addons:
  apt:
    update: true
  apt_packages:
      - libgmp-dev
      - libmpfr-dev
      - libflint-dev
      - libboost-dev
      - autoconf
      - automake
      - libtool
env:
  - EANTIC=no
  - EANTIC=yes

# send email notifications if master branch starts failing
# or stops failing
notifications:
  email:
    if: branch = master
    recipients:
      - max@quendi.de
      - wbruns@uos.de
    on_success: change
    on_failure: change

install:
  - export MAKEFLAGS="-j2"
  - export PIP=$(which pip) # workaround so that sudo uses correct pip
  - pip install coverage
  # install normaliz
  - ./.travis-install-normaliz.sh

script:
  # build pynormaliz
  - export CFLAGS="$CFLAGS --coverage"
  - export PYTHONPATH="$PWD"
  - python setup.py build_ext --inplace
  # run tests
  - export OMP_NUM_THREADS=4
  - coverage run tests/runtests.py
  # make source distribution, install from it
  # and check that the module can be imported
  - python setup.py sdist
  - sudo $PIP install --no-index --no-deps -v dist/PyNormaliz-*.tar.gz
  - python -c "import PyNormaliz"

after_script:
  - bash <(curl -s https://codecov.io/bash)
